// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdI7MwYUAB08y2Tkwy10bCrD9CIaRMR7c',
    appId: '1:734373727761:android:1b8446bec6b06c8a792bb0',
    messagingSenderId: '734373727761',
    projectId: 'meditate-a86dd',
    storageBucket: 'meditate-a86dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-VHav_i_kp_kq02sdYPcj4O01kiV-CI',
    appId: '1:734373727761:ios:68a776f6edea0600792bb0',
    messagingSenderId: '734373727761',
    projectId: 'meditate-a86dd',
    storageBucket: 'meditate-a86dd.firebasestorage.app',
    androidClientId: '734373727761-ga6gf6aqbr2i0d7rvt6cr65rrnhlrqjk.apps.googleusercontent.com',
    iosClientId: '734373727761-fh8jjnaske1tcbb7glula4kopvpeh624.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditate',
  );
}
